name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Executa automaticamente a cada 12 horas
  workflow_dispatch: # Permite a execução manual na aba Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "♻️ Atualiza animação da cobrinha de commits"
          file_pattern: "github-contribution-grid-snake*.svg"
